apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: prepull
spec:
  selector:
    matchLabels:
      prepull-test-images: loadtest
  template:
    metadata:
      labels:
        prepull-test-images: loadtest
    spec:
      nodeSelector:
        kubernetes.io/os: windows
      containers:
      - image: gcr.io/gke-release/pause-win:1.2.1
        name: pause
      - image: mcr.microsoft.com/windows/servercore/iis
        name: iis
      tolerations:
      - key: "node.kubernetes.io/os"
        operator: "Exists"
        effect: "NoSchedule"
