apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: prepull-test-containers
spec:
  selector:
    matchLabels:
      prepull-test-images: e2e
  template:
    metadata:
      labels:
        prepull-test-images: e2e
    spec:
      nodeSelector:
        kubernetes.io/os: windows
      # To generate this list from the build-log.txt output of an e2e test
      # result:
      #   grep -o -E 'e2eteam/([[:alnum:]_-]+):([[:alnum:]./_-]+)' \
      #   build-log.txt | sort | uniq
      # DaemonSets do not support a RestartPolicy other than 'Always', so we
      # run ping in each container to keep it alive so that kubernetes does not
      # continually restart the containers while we're prepulling.
      containers:
      - image: e2eteam/busybox:1.29
        name: busybox1
        resources:
          requests:
            cpu: 1m
        command: ['cmd.exe', '/c', 'ping -n 1800 127.0.0.1 >NUL']
      - image: e2eteam/curl:1803
        name: curl2
        resources:
          requests:
            cpu: 1m
        command: ['cmd.exe', '/c', 'ping -n 1800 127.0.0.1 >NUL']
      - image: e2eteam/java:openjdk-8-jre
        name: java3
        resources:
          requests:
            cpu: 1m
        command: ['cmd.exe', '/c', 'ping -n 1800 127.0.0.1 >NUL']
      - image: e2eteam/test-webserver:1.0
        name: test-webserver4
        resources:
          requests:
            cpu: 1m
        command: ['cmd.exe', '/c', 'ping -n 1800 127.0.0.1 >NUL']
      - image: e2eteam/cassandra:v13
        name: cassandra5
        resources:
          requests:
            cpu: 1m
        command: ['cmd.exe', '/c', 'ping -n 1800 127.0.0.1 >NUL']
      - image: e2eteam/dnsutils:1.1
        name: dnsutils6
        resources:
          requests:
            cpu: 1m
        command: ['cmd.exe', '/c', 'ping -n 1800 127.0.0.1 >NUL']
      - image: e2eteam/echoserver:2.2
        name: echoserver7
        resources:
          requests:
            cpu: 1m
        command: ['cmd.exe', '/c', 'ping -n 1800 127.0.0.1 >NUL']
      - image: e2eteam/entrypoint-tester:1.0
        name: entrypoint-tester8
        resources:
          requests:
            cpu: 1m
        command: ['cmd.exe', '/c', 'ping -n 1800 127.0.0.1 >NUL']
      - image: e2eteam/etcd:v3.3.10
        name: etcd9
        resources:
          requests:
            cpu: 1m
        command: ['cmd.exe', '/c', 'ping -n 1800 127.0.0.1 >NUL']
      - image: e2eteam/etcd:3.3.10
        name: etcd10
        resources:
          requests:
            cpu: 1m
        command: ['cmd.exe', '/c', 'ping -n 1800 127.0.0.1 >NUL']
      - image: e2eteam/fakegitserver:1.0
        name: fakegitserver11
        resources:
          requests:
            cpu: 1m
        command: ['cmd.exe', '/c', 'ping -n 1800 127.0.0.1 >NUL']
      - image: e2eteam/gb-frontend:v6
        name: gb-frontend12
        resources:
          requests:
            cpu: 1m
        command: ['cmd.exe', '/c', 'ping -n 1800 127.0.0.1 >NUL']
      - image: e2eteam/gb-redisslave:v3
        name: gb-redisslave13
        resources:
          requests:
            cpu: 1m
        command: ['cmd.exe', '/c', 'ping -n 1800 127.0.0.1 >NUL']
      - image: e2eteam/hazelcast-kubernetes:3.8_1
        name: hazelcast-kubernetes14
        resources:
          requests:
            cpu: 1m
        command: ['cmd.exe', '/c', 'ping -n 1800 127.0.0.1 >NUL']
      - image: e2eteam/hostexec:1.1
        name: hostexec15
        resources:
          requests:
            cpu: 1m
        command: ['cmd.exe', '/c', 'ping -n 1800 127.0.0.1 >NUL']
      - image: e2eteam/iperf:1.0
        name: iperf16
        resources:
          requests:
            cpu: 1m
        command: ['cmd.exe', '/c', 'ping -n 1800 127.0.0.1 >NUL']
      - image: e2eteam/jessie-dnsutils:1.0
        name: jessie-dnsutils17
        resources:
          requests:
            cpu: 1m
        command: ['cmd.exe', '/c', 'ping -n 1800 127.0.0.1 >NUL']
      - image: e2eteam/kitten:1.0
        name: kitten18
        resources:
          requests:
            cpu: 1m
        command: ['cmd.exe', '/c', 'ping -n 1800 127.0.0.1 >NUL']
      - image: e2eteam/liveness:1.1
        name: liveness19
        resources:
          requests:
            cpu: 1m
        command: ['cmd.exe', '/c', 'ping -n 1800 127.0.0.1 >NUL']
      - image: e2eteam/logs-generator:1.0
        name: logs-generator20
        resources:
          requests:
            cpu: 1m
        command: ['cmd.exe', '/c', 'ping -n 1800 127.0.0.1 >NUL']
      - image: e2eteam/mounttest:1.0
        name: mounttest21
        resources:
          requests:
            cpu: 1m
        command: ['cmd.exe', '/c', 'ping -n 1800 127.0.0.1 >NUL']
      - image: e2eteam/nautilus:1.0
        name: nautilus22
        resources:
          requests:
            cpu: 1m
        command: ['cmd.exe', '/c', 'ping -n 1800 127.0.0.1 >NUL']
      - image: e2eteam/net:1.0
        name: net23
        resources:
          requests:
            cpu: 1m
        command: ['cmd.exe', '/c', 'ping -n 1800 127.0.0.1 >NUL']
      - image: e2eteam/netexec:1.1
        name: netexec24
        resources:
          requests:
            cpu: 1m
        command: ['cmd.exe', '/c', 'ping -n 1800 127.0.0.1 >NUL']
      - image: e2eteam/nettest:1.0
        name: nettest25
        resources:
          requests:
            cpu: 1m
        command: ['cmd.exe', '/c', 'ping -n 1800 127.0.0.1 >NUL']
      - image: e2eteam/nginx:1.14-alpine
        name: nginx26
        resources:
          requests:
            cpu: 1m
        command: ['cmd.exe', '/c', 'ping -n 1800 127.0.0.1 >NUL']
      - image: e2eteam/nginx:1.15-alpine
        name: nginx27
        resources:
          requests:
            cpu: 1m
        command: ['cmd.exe', '/c', 'ping -n 1800 127.0.0.1 >NUL']
      - image: e2eteam/no-snat-test:1.0
        name: no-snat-test28
        resources:
          requests:
            cpu: 1m
        command: ['cmd.exe', '/c', 'ping -n 1800 127.0.0.1 >NUL']
      - image: e2eteam/pause:3.1
        name: pause29
        resources:
          requests:
            cpu: 1m
        command: ['cmd.exe', '/c', 'ping -n 1800 127.0.0.1 >NUL']
      - image: e2eteam/port-forward-tester:1.0
        name: port-forward-tester30
        resources:
          requests:
            cpu: 1m
        command: ['cmd.exe', '/c', 'ping -n 1800 127.0.0.1 >NUL']
      - image: e2eteam/porter:1.0
        name: porter31
        resources:
          requests:
            cpu: 1m
        command: ['cmd.exe', '/c', 'ping -n 1800 127.0.0.1 >NUL']
      - image: e2eteam/redis:1.0
        name: redis32
        resources:
          requests:
            cpu: 1m
        command: ['cmd.exe', '/c', 'ping -n 1800 127.0.0.1 >NUL']
      - image: e2eteam/resource-consumer:1.4
        name: resource-consumer33-1
        resources:
          requests:
            cpu: 1m
        command: ['cmd.exe', '/c', 'ping -n 1800 127.0.0.1 >NUL']
      - image: e2eteam/resource-consumer:1.5
        name: resource-consumer33-2
        resources:
          requests:
            cpu: 1m
        command: ['cmd.exe', '/c', 'ping -n 1800 127.0.0.1 >NUL']
      - image: e2eteam/resource-consumer-controller:1.0
        name: resource-consumer-controller34
        resources:
          requests:
            cpu: 1m
        command: ['cmd.exe', '/c', 'ping -n 1800 127.0.0.1 >NUL']
      - image: e2eteam/rethinkdb:1.16.0_1
        name: rethinkdb35
        resources:
          requests:
            cpu: 1m
        command: ['cmd.exe', '/c', 'ping -n 1800 127.0.0.1 >NUL']
      - image: e2eteam/sample-apiserver:1.10
        name: sample-apiserver36
        resources:
          requests:
            cpu: 1m
        command: ['cmd.exe', '/c', 'ping -n 1800 127.0.0.1 >NUL']
      - image: e2eteam/serve-hostname:1.1
        name: serve-hostname37
        resources:
          requests:
            cpu: 1m
        command: ['cmd.exe', '/c', 'ping -n 1800 127.0.0.1 >NUL']
      - image: e2eteam/webhook:1.13v1
        name: webhook38
        resources:
          requests:
            cpu: 1m
        command: ['cmd.exe', '/c', 'ping -n 1800 127.0.0.1 >NUL']
